# Generated by Django 2.2.2 on 2021-05-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbworm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_name', models.CharField(blank=True, db_column='Gene_name', max_length=255, null=True)),
                ('organism', models.CharField(blank=True, db_column='Organism', max_length=255, null=True)),
                ('evidece_level', models.CharField(blank=True, db_column='Evidece_level', max_length=255, null=True)),
                ('intron', models.CharField(blank=True, db_column='Intron', max_length=255, null=True)),
                ('signal_peptide', models.CharField(blank=True, db_column='Signal_Peptide', max_length=255, null=True)),
                ('tmhmm', models.CharField(blank=True, db_column='TMHMM', max_length=255, null=True)),
                ('pmid', models.CharField(blank=True, db_column='Pmid', max_length=255, null=True)),
                ('molecular_weight', models.CharField(blank=True, db_column='Molecular_Weight', max_length=255, null=True)),
                ('domains', models.CharField(blank=True, db_column='Domains', max_length=255, null=True)),
                ('date_source', models.CharField(blank=True, db_column='Date_Source', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbworm',
                'managed': False,
            },
        ),
    ]
