# Generated by Django 2.2.2 on 2021-06-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_new_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_entries',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='保存日期'),
        ),
    ]
