# Generated by Django 2.2.2 on 2021-06-23 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_new_entries_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_entries',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
    ]
