# Generated by Django 2.2.2 on 2021-06-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_auto_20210623_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_entries',
            name='email',
            field=models.EmailField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='new_entries',
            name='gene_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='new_entries',
            name='more',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='new_entries',
            name='organism',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
