# Generated by Django 2.2.2 on 2021-06-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0008_new_entries_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_entries',
            name='state',
        ),
        migrations.AddField(
            model_name='new_entries',
            name='read_sum',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
