# Generated by Django 2.2.2 on 2021-06-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0009_auto_20210624_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_entries',
            name='read_sum',
            field=models.IntegerField(default=1, max_length=6),
        ),
    ]
