# Generated by Django 2.2.2 on 2021-06-24 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0010_auto_20210624_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comment',
            name='read_sum',
            field=models.IntegerField(default=1, max_length=6),
        ),
        migrations.AddField(
            model_name='user_comment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
    ]
