# Generated by Django 2.2.2 on 2021-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dba_manager',
            name='code',
            field=models.CharField(default='abcd', max_length=4),
        ),
    ]
