# Generated by Django 2.2.2 on 2021-06-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBA', '0004_auto_20210621_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='dba_manager',
            name='original_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
