# Generated by Django 2.2.2 on 2021-06-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBA', '0005_dba_manager_original_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dba_manager',
            name='code',
            field=models.CharField(default='-', max_length=4, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='dba_manager',
            name='email',
            field=models.EmailField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='dba_manager',
            name='name',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
