# Generated by Django 2.2.2 on 2021-06-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBA', '0006_auto_20210621_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='dba_manager',
            name='add_by',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='dba_manager',
            name='del_by',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='dba_manager',
            name='save_by',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
