# Generated by Django 2.2.2 on 2021-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBA', '0007_auto_20210622_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='dba_manager',
            name='password',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
