# Generated by Django 2.2.2 on 2021-06-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBA', '0008_dba_manager_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dba_manager',
            name='password',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
