# Generated by Django 2.2.2 on 2021-06-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBA', '0009_auto_20210623_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='dba_manager',
            name='read_count',
            field=models.IntegerField(default='0', max_length=2),
        ),
    ]
