# Generated by Django 2.2.2 on 2021-06-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBA', '0010_dba_manager_read_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dba_manager',
            name='read_count',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
