# Generated by Django 2.2.2 on 2021-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBA', '0011_auto_20210624_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='dba_manager',
            name='read_count_u',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='dba_manager',
            name='read_count',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
